output: output

files:
  - interface.template
  - entity.template
  - model.template
  - controller.template

output_names:
  - 'I{{class_name}}.ts'
  - '{{class_name}}.ts'
  - '{{class_name}}Model.ts'
  - '{{class_name}}Controller.ts'

output_directories:
  - 'interfaces'
  - 'entities'
  - 'models'
  - 'controllers'
